# Generated by Django 4.1.6 on 2023-02-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_murojat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=30)),
                ('lavozimi', models.CharField(max_length=40)),
                ('malumot', models.TextField()),
                ('tarmoq', models.CharField(max_length=40)),
                ('rasm', models.ImageField(upload_to='media')),
            ],
        ),
    ]
