# Generated by Django 4.1.6 on 2023-02-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='tarmoq',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='team',
            name='inn',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
